/*
 * ACT Core API
 *
 * API documentation for ACT Core system
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import "act-core-api/internal/models"

type DataGathererTreeNode = models.DataGathererTreeNode
